const ClubPlayersRegistrationActionTypes = {
    ON_CLUB_PLAYERS_REGISTRATION_START: 'ON_CLUB_PLAYERS_REGISTRATION_START',
    ON_CLUB_PLAYERS_REGISTRATION_SUCCESS: 'ON_CLUB_PLAYERS_REGISTRATION_SUCCESS',
    ON_CLUB_PLAYERS_REGISTRATION_FAIL: 'ON_CLUB_PLAYERS_REGISTRATION_FAIL',
    ON_CLUB_PLAYERS_CREATE: 'ON_CLUB_PLAYERS_CREATE',
    ON_CLUB_PLAYERS_LIST_UPDATE: 'ON_CLUB_PLAYERS_LIST_UPDATE',
    ON_CLUB_PLAYERS_ERROR_MESSAGE_UPDATE: 'ON_CLUB_PLAYERS_ERROR_MESSAGE_UPDATE',

};

export default ClubPlayersRegistrationActionTypes;