const LoginActionTypes = {
    ON_LOGIN_REQUEST_START: 'LOGIN_REQUEST_START',
    ON_LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    ON_LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
    ON_LOGIN_FORM_CLEAR: 'LOGIN_FORM_CLEAR'
};

export default LoginActionTypes;